# GIT:
# To stop tracking config.yaml:
#   git update-index --assume-unchanged config.yaml
# To start tracking again:
#   git update-index --no-assume-unchanged config.yaml


filename_formats: [
    "{parent_dir}/{source}/{community}/[{date_uploaded}] {title};opt (item-{item_num:d});opt [{secondary_source_id:S}];opt [{source_id:S}].{ext}",
    "{parent_dir}/{title}.{ext}",
]


media_folders:
    # - A:\Whispera\gallery-dl\bluesky
    # - A:\Whispera\gallery-dl\reddit
    - A:\Whispera\gallery-dl
    # - A:\Whispera\gallery-dl\3dHentai\AnimX
    # - A:\Whispera\gallery-dl\fapello
